### ISSUE TITLE
Won't create a Cookie after click on "Accept"

### ISSUE THREAD

**Issue by stanislavhannes** [adriandmitroca/cookie-consent-box#12]
Hi, 
I am using your module with Nuxt 2.11.0 and It looks perfect. 
It also hides after I click on "Accept" but it won't create a cookie for the user. 
Therefor after a reload the box appears again. 
Do you have any idea what the problem could be?
Thank you!

**Comment by adriandmitroca** [comment]
Hi Stanislav,

I am not using Nuxt on daily basis, but I presume that you are rendering it on server side - probably it shouldn't be rendered there, especially that is not something that should be grabbed by bots or SERPs.

This package uses `js-cookies` from npm, which uses `document.cookie` behind the scenes, that most likely is not available in Nuxt.

With that in mind, imho cookie consent should be rendered only on client side.

Probably that's not much helpful to you, anyways, let me know if you'll figure out issue - I am curious what this actually is.

**Comment by stanislavhannes** [comment]
Hey,
yes that's correct I am using it in SSR mode, but I use this as a "plugin" in Nuxt which is only rendered on client side. Otherwise it wouldn't even display the banner, because it wouldn't find the `document` root. 

Sure, if I find a solution I will let u know!
