### ISSUE TITLE
It appears on every reload

### ISSUE THREAD

**Issue by sergiovcs** [adriandmitroca/cookie-consent-box#13]
Hi, 
Thanks for creating such an amazing cookie consent box. 
I'm testing it and the box appears every time I reload the page.  This is happening in all the browsers I tried.
As far as I understand in the documentation, it should be hidden for 365 days when clicking Accept (I didn't modify the default value). 

I didn't modify the CSS or JS before copying them to my website and I just updated the background color and language when calling the script from my index.html.

Do you know what could be causing this trouble? 

Thanks in advance!

**Comment by adriandmitroca** [comment]
Hey,

Yes, 365 days is the default for storing the consent cookie. I don't recall having this issue and the plugin is used on more than 50 sites at the moment.

Perhaps there's issue with your browser / extensions installed in it? It seems that persisting cookie in the browser's memory isn't happening on your machine.

**Comment by sergiovcs** [comment]
> Hey,
> 
> Yes, 365 days is the default for storing the consent cookie. I don't recall having this issue and the plugin is used on more than 50 sites at the moment.
> 
> Perhaps there's issue with your browser / extensions installed in it? It seems that persisting cookie in the browser's memory isn't happening on your machine.

Thanks for your answer! 

Best regards!

**Comment by adriandmitroca** [comment]
That's easy ;)

You pass this option parameter to the constructor: 
`cookieKey: 'cookie-key-' + Math.random()`

This makes the cookie unique for every page visit, so it's persisted always to the different cookie. This needs to be permanent value, not randomised one.

**Comment by sergiovcs** [comment]
> That's easy ;)
> 
> You pass this option parameter to the constructor:
> `cookieKey: 'cookie-key-' + Math.random()`
> 
> This makes the cookie unique for every page visit, so it's persisted always to the different cookie. This needs to be permanent value, not randomised one.

That's true, I didn't realize! Thanks so much for answering so fast! 
My next task will be to edit CSS so I move the button to the left and I modify the button appearance when hovering   :) I hope to make it fast 

By the way, you can add my Spanish translation to the project if you want to. 

Best regards and, once again, THANKS

**Comment by adriandmitroca** [comment]
No problem, happy to help
